declare const styles: {
  readonly "absolute": string;
  readonly "block": string;
  readonly "blur!": string;
  readonly "blur": string;
  readonly "border": string;
  readonly "break-all": string;
  readonly "container": string;
  readonly "contents": string;
  readonly "custom-scroll-container": string;
  readonly "custom-scroll-content": string;
  readonly "custom-scrollbar-thumb": string;
  readonly "custom-scrollbar-track": string;
  readonly "dragging": string;
  readonly "drop-shadow": string;
  readonly "filter": string;
  readonly "fixed": string;
  readonly "flex": string;
  readonly "font-bold": string;
  readonly "grid": string;
  readonly "hidden": string;
  readonly "inline-flex": string;
  readonly "invisible": string;
  readonly "lowercase": string;
  readonly "outline": string;
  readonly "relative": string;
  readonly "resize": string;
  readonly "rounded": string;
  readonly "shadow": string;
  readonly "static": string;
  readonly "table": string;
  readonly "text-3xl": string;
  readonly "transition": string;
  readonly "underline": string;
  readonly "visible": string;
};
export = styles;

